version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          REACT_APP_NODE_PATH: ./
          NODE_PATH: ./
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Running E2E tests
          command: yarn cypress:ci
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
          - ~/.cache/yarn
