version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "react"
      - match:
          dependency_name: "react-dom"
      - match:
          dependency_name: "@types/react"
      - match:
          dependency_name: "@types/react-dom"
      - match:
          dependency_name: "react-cache"
      - match:
          dependency_name: "@types/react-cache"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
